
language: java
jdk:
  - oraclejdk11
branches:
  only:
    - heroku
    - develop
    - /^release-.*$/
    - master
notifications:
  email:
    recipients:
      - carloshernandcasares@gmail.es
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
dist:
  trusty
script:
  #Test
  #- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - echo "skipping tests"
  # Subir a sonarcloud
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=carloshdzcasares -Dsonar.login=$SONAR
deploy:
  provider: heroku
  api_key: $HEROKU
  on:
    branch: heroku
  app: apitweet


